# docker-compose.yml
version: '3.8'

services:
  geotileify:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run ./cmd/geotileify
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp
      - ./migrations:/app/migrations
    restart: unless-stopped
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"  # Untuk akses ke localhost dari container
    networks:
      - administration_id_default

networks:
  administration_id_default:
    external: true
